// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {connections} from '../models';

export function AddActionTarget(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddPersonTag(arg1:string,arg2:string,arg3:string):Promise<main.TagInfo>;

export function ClearLogs():Promise<void>;

export function CreateAction(arg1:main.CreateActionRequest):Promise<main.ActionInfo>;

export function DeleteAction(arg1:string):Promise<void>;

export function DeleteCredential(arg1:string):Promise<void>;

export function DeleteSession(arg1:number):Promise<void>;

export function DeleteWorkflow(arg1:string):Promise<void>;

export function ExecuteAction(arg1:string):Promise<void>;

export function GetAction(arg1:string):Promise<main.ActionInfo>;

export function GetActionTargets(arg1:string):Promise<Array<main.TargetInfo>>;

export function GetActions(arg1:string,arg2:string,arg3:number):Promise<Array<main.ActionInfo>>;

export function GetAllTags():Promise<Array<main.TagInfo>>;

export function GetAvailableActionTypes():Promise<Record<string, Array<string>>>;

export function GetConnectionsForPlatform(arg1:string):Promise<Array<connections.Connection>>;

export function GetDBPath():Promise<string>;

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetPeople(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<main.PersonInfo>>;

export function GetPeopleCount(arg1:string,arg2:string):Promise<number>;

export function GetPeopleTagsMap(arg1:Array<string>):Promise<Record<string, Array<main.TagInfo>>>;

export function GetPersonDetail(arg1:string):Promise<main.PersonDetailInfo>;

export function GetPersonInteractions(arg1:string):Promise<Array<main.PersonInteraction>>;

export function GetPersonTags(arg1:string):Promise<Array<main.TagInfo>>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function GetSocialLists():Promise<Array<main.SocialListInfo>>;

export function GetTemplates():Promise<Array<main.TemplateInfo>>;

export function GetWorkflow(arg1:string):Promise<main.WorkflowDetail>;

export function GetWorkflowExecutions(arg1:string,arg2:number):Promise<Array<main.WorkflowExecutionSummary>>;

export function GetWorkflowNodeTypes():Promise<Record<string, any>>;

export function IsDBConnected():Promise<boolean>;

export function ListConnections(arg1:string):Promise<Array<connections.Connection>>;

export function ListCredentials():Promise<Array<main.CredentialSummary>>;

export function ListPlatformsJSON(arg1:string):Promise<string>;

export function ListWorkflows():Promise<Array<main.WorkflowSummary>>;

export function OpenURL(arg1:string):Promise<void>;

export function RemoveConnection(arg1:string):Promise<string>;

export function RemovePersonTag(arg1:string,arg2:string):Promise<void>;

export function RunNode(arg1:main.NodeRunRequest):Promise<main.NodeRunResult>;

export function RunWorkflow(arg1:string):Promise<void>;

export function SaveConnectionDirect(arg1:string,arg2:string,arg3:Record<string, any>):Promise<string>;

export function SaveCredential(arg1:main.SaveCredentialRequest):Promise<main.CredentialSummary>;

export function SaveWorkflow(arg1:main.SaveWorkflowRequest):Promise<main.WorkflowSummary>;

export function SetWorkflowActive(arg1:string,arg2:boolean):Promise<void>;

export function TestConnection(arg1:string):Promise<string>;

export function UpdateActionParams(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateActionState(arg1:string,arg2:string):Promise<void>;
