// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddActionTarget(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddActionTarget'](arg1, arg2, arg3);
}

export function AddPersonTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPersonTag'](arg1, arg2, arg3);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateAction(arg1) {
  return window['go']['main']['App']['CreateAction'](arg1);
}

export function DeleteAction(arg1) {
  return window['go']['main']['App']['DeleteAction'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function ExecuteAction(arg1) {
  return window['go']['main']['App']['ExecuteAction'](arg1);
}

export function GetAction(arg1) {
  return window['go']['main']['App']['GetAction'](arg1);
}

export function GetActionTargets(arg1) {
  return window['go']['main']['App']['GetActionTargets'](arg1);
}

export function GetActions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetActions'](arg1, arg2, arg3);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAvailableActionTypes() {
  return window['go']['main']['App']['GetAvailableActionTypes']();
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPeople(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPeople'](arg1, arg2, arg3, arg4);
}

export function GetPeopleCount(arg1, arg2) {
  return window['go']['main']['App']['GetPeopleCount'](arg1, arg2);
}

export function GetPeopleTagsMap(arg1) {
  return window['go']['main']['App']['GetPeopleTagsMap'](arg1);
}

export function GetPersonDetail(arg1) {
  return window['go']['main']['App']['GetPersonDetail'](arg1);
}

export function GetPersonInteractions(arg1) {
  return window['go']['main']['App']['GetPersonInteractions'](arg1);
}

export function GetPersonTags(arg1) {
  return window['go']['main']['App']['GetPersonTags'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSocialLists() {
  return window['go']['main']['App']['GetSocialLists']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function IsDBConnected() {
  return window['go']['main']['App']['IsDBConnected']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RemovePersonTag(arg1, arg2) {
  return window['go']['main']['App']['RemovePersonTag'](arg1, arg2);
}

export function UpdateActionState(arg1, arg2) {
  return window['go']['main']['App']['UpdateActionState'](arg1, arg2);
}
