// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddActionTarget(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddActionTarget'](arg1, arg2, arg3);
}

export function AddPersonTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPersonTag'](arg1, arg2, arg3);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateAction(arg1) {
  return window['go']['main']['App']['CreateAction'](arg1);
}

export function DeleteAction(arg1) {
  return window['go']['main']['App']['DeleteAction'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['main']['App']['DeleteCredential'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['main']['App']['DeleteWorkflow'](arg1);
}

export function ExecuteAction(arg1) {
  return window['go']['main']['App']['ExecuteAction'](arg1);
}

export function GetAction(arg1) {
  return window['go']['main']['App']['GetAction'](arg1);
}

export function GetActionTargets(arg1) {
  return window['go']['main']['App']['GetActionTargets'](arg1);
}

export function GetActions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetActions'](arg1, arg2, arg3);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAvailableActionTypes() {
  return window['go']['main']['App']['GetAvailableActionTypes']();
}

export function GetConnectionsForPlatform(arg1) {
  return window['go']['main']['App']['GetConnectionsForPlatform'](arg1);
}

export function GetOAuthCredentials(arg1) {
  return window['go']['main']['App']['GetOAuthCredentials'](arg1);
}

export function SetOAuthCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetOAuthCredentials'](arg1, arg2, arg3);
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPeople(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPeople'](arg1, arg2, arg3, arg4);
}

export function GetPeopleCount(arg1, arg2) {
  return window['go']['main']['App']['GetPeopleCount'](arg1, arg2);
}

export function GetPeopleTagsMap(arg1) {
  return window['go']['main']['App']['GetPeopleTagsMap'](arg1);
}

export function GetPersonDetail(arg1) {
  return window['go']['main']['App']['GetPersonDetail'](arg1);
}

export function GetPersonInteractions(arg1) {
  return window['go']['main']['App']['GetPersonInteractions'](arg1);
}

export function GetPersonTags(arg1) {
  return window['go']['main']['App']['GetPersonTags'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSocialLists() {
  return window['go']['main']['App']['GetSocialLists']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetWorkflow(arg1) {
  return window['go']['main']['App']['GetWorkflow'](arg1);
}

export function GetWorkflowExecutions(arg1, arg2) {
  return window['go']['main']['App']['GetWorkflowExecutions'](arg1, arg2);
}

export function GetRecentExecutions(arg1) {
  return window['go']['main']['App']['GetRecentExecutions'](arg1);
}

export function GetWorkflowNodeTypes() {
  return window['go']['main']['App']['GetWorkflowNodeTypes']();
}

export function IsDBConnected() {
  return window['go']['main']['App']['IsDBConnected']();
}

export function ListConnections(arg1) {
  return window['go']['main']['App']['ListConnections'](arg1);
}

export function ListCredentialsForNode(arg1) {
  return window['go']['main']['App']['ListCredentialsForNode'](arg1);
}

export function LoginSocial(arg1) {
  return window['go']['main']['App']['LoginSocial'](arg1);
}

export function ListCredentials() {
  return window['go']['main']['App']['ListCredentials']();
}

export function ListPlatformsJSON(arg1) {
  return window['go']['main']['App']['ListPlatformsJSON'](arg1);
}

export function ListWorkflows() {
  return window['go']['main']['App']['ListWorkflows']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RemoveConnection(arg1) {
  return window['go']['main']['App']['RemoveConnection'](arg1);
}

export function RemovePersonTag(arg1, arg2) {
  return window['go']['main']['App']['RemovePersonTag'](arg1, arg2);
}

export function RunNode(arg1) {
  return window['go']['main']['App']['RunNode'](arg1);
}

export function RunWorkflow(arg1) {
  return window['go']['main']['App']['RunWorkflow'](arg1);
}

export function ConnectPlatformOAuth(arg1) {
  return window['go']['main']['App']['ConnectPlatformOAuth'](arg1);
}

export function SaveConnectionDirect(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConnectionDirect'](arg1, arg2, arg3);
}

export function SaveCredential(arg1) {
  return window['go']['main']['App']['SaveCredential'](arg1);
}

export function SaveWorkflow(arg1) {
  return window['go']['main']['App']['SaveWorkflow'](arg1);
}

export function SetWorkflowActive(arg1, arg2) {
  return window['go']['main']['App']['SetWorkflowActive'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateActionParams(arg1, arg2) {
  return window['go']['main']['App']['UpdateActionParams'](arg1, arg2);
}

export function UpdateActionState(arg1, arg2) {
  return window['go']['main']['App']['UpdateActionState'](arg1, arg2);
}

export function ListAIProviders() {
  return window['go']['main']['App']['ListAIProviders']();
}

export function SaveAIProvider(arg1) {
  return window['go']['main']['App']['SaveAIProvider'](arg1);
}

export function DeleteAIProvider(arg1) {
  return window['go']['main']['App']['DeleteAIProvider'](arg1);
}

export function TestAIProvider(arg1) {
  return window['go']['main']['App']['TestAIProvider'](arg1);
}

export function GetAIModels(arg1) {
  return window['go']['main']['App']['GetAIModels'](arg1);
}

export function GetAIRegistry() {
  return window['go']['main']['App']['GetAIRegistry']();
}

export function StreamAIChat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StreamAIChat'](arg1, arg2, arg3, arg4);
}

export function GetAIChatHistory(arg1) {
  return window['go']['main']['App']['GetAIChatHistory'](arg1);
}

export function ClearAIChatHistory(arg1) {
  return window['go']['main']['App']['ClearAIChatHistory'](arg1);
}

export function ListResources(platform, resourceType, credentialID, query) {
  return window['go']['main']['App']['ListResources'](platform, resourceType, credentialID, query);
}

export function CreateResource(platform, resourceType, credentialID, name) {
  return window['go']['main']['App']['CreateResource'](platform, resourceType, credentialID, name);
}
