// Wails v2 Go bindings — auto-generated stubs.
// These are overwritten by `wails build`. Created to enable IDE imports.
import { Call } from '../../runtime/runtime'

export const GetDashboardStats    = ()             => Call('main.App.GetDashboardStats')
export const GetActions           = (p, s, l)      => Call('main.App.GetActions', p, s, l)
export const GetAction            = (id)           => Call('main.App.GetAction', id)
export const CreateAction         = (req)          => Call('main.App.CreateAction', req)
export const UpdateActionState    = (id, state)    => Call('main.App.UpdateActionState', id, state)
export const DeleteAction         = (id)           => Call('main.App.DeleteAction', id)
export const ExecuteAction        = (id)           => Call('main.App.ExecuteAction', id)
export const GetActionTargets     = (actionId)     => Call('main.App.GetActionTargets', actionId)
export const AddActionTarget      = (a, l, p)      => Call('main.App.AddActionTarget', a, l, p)
export const GetPeople            = (p, s, l, o)   => Call('main.App.GetPeople', p, s, l, o)
export const GetPeopleCount       = (p, s)         => Call('main.App.GetPeopleCount', p, s)
export const GetSessions          = ()             => Call('main.App.GetSessions')
export const DeleteSession        = (id)           => Call('main.App.DeleteSession', id)
export const GetSocialLists       = ()             => Call('main.App.GetSocialLists')
export const GetTemplates         = ()             => Call('main.App.GetTemplates')
export const GetLogs              = ()             => Call('main.App.GetLogs')
export const ClearLogs            = ()             => Call('main.App.ClearLogs')
export const GetAvailableActionTypes = ()          => Call('main.App.GetAvailableActionTypes')
export const GetDBPath            = ()             => Call('main.App.GetDBPath')
export const IsDBConnected        = ()             => Call('main.App.IsDBConnected')
export const OpenURL              = (url)          => Call('main.App.OpenURL', url)
export const GetPersonDetail      = (id)           => Call('main.App.GetPersonDetail', id)
export const GetPersonInteractions= (id)           => Call('main.App.GetPersonInteractions', id)
export const GetAllTags           = ()             => Call('main.App.GetAllTags')
export const GetPersonTags        = (personId)     => Call('main.App.GetPersonTags', personId)
export const AddPersonTag         = (pId, n, c)    => Call('main.App.AddPersonTag', pId, n, c)
export const RemovePersonTag      = (pId, tId)     => Call('main.App.RemovePersonTag', pId, tId)
export const GetPeopleTagsMap     = (ids)          => Call('main.App.GetPeopleTagsMap', ids)
