package ai

// ProviderDef defines an AI provider's capabilities and configuration.
type ProviderDef struct {
	ID             string     `json:"id"`
	Name           string     `json:"name"`
	IconEmoji      string     `json:"icon_emoji"`
	Category       string     `json:"category"` // "frontier","cloud","inference","gateway","other"
	Tier           string     `json:"tier"`      // "known" | "gateway"
	DefaultBaseURL string     `json:"default_base_url"`
	AuthLabel      string     `json:"auth_label"`
	Models         []ModelDef `json:"models"`
	Adapter        string     `json:"adapter"` // "openai","anthropic","google","bedrock"
	DocsURL        string     `json:"docs_url"`
}

// ModelDef describes a single model offered by a provider.
type ModelDef struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	ContextWindow int      `json:"context_window"`
	Capabilities  []string `json:"capabilities"` // "chat","vision","tools","embed"
}

// ProviderRegistry is the canonical list of all supported AI providers.
var ProviderRegistry = []ProviderDef{

	// ─── Frontier ─────────────────────────────────────────────────────────────

	{
		ID:             "openai",
		Name:           "OpenAI",
		IconEmoji:      "🤖",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://api.openai.com/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://platform.openai.com/docs",
		Models: []ModelDef{
			{ID: "gpt-4o", Name: "GPT-4o", ContextWindow: 128000, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "gpt-4o-mini", Name: "GPT-4o Mini", ContextWindow: 128000, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "gpt-4-turbo", Name: "GPT-4 Turbo", ContextWindow: 128000, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "o1", Name: "o1", ContextWindow: 200000, Capabilities: []string{"chat"}},
			{ID: "o1-mini", Name: "o1 Mini", ContextWindow: 128000, Capabilities: []string{"chat"}},
			{ID: "o3-mini", Name: "o3 Mini", ContextWindow: 200000, Capabilities: []string{"chat", "tools"}},
			{ID: "text-embedding-3-small", Name: "Text Embedding 3 Small", ContextWindow: 8191, Capabilities: []string{"embed"}},
			{ID: "text-embedding-3-large", Name: "Text Embedding 3 Large", ContextWindow: 8191, Capabilities: []string{"embed"}},
		},
	},
	{
		ID:             "anthropic",
		Name:           "Anthropic",
		IconEmoji:      "🔬",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://api.anthropic.com/v1",
		AuthLabel:      "API Key",
		Adapter:        "anthropic",
		DocsURL:        "https://docs.anthropic.com",
		Models: []ModelDef{
			{ID: "claude-opus-4-6", Name: "Claude Opus 4", ContextWindow: 200000, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "claude-sonnet-4-6", Name: "Claude Sonnet 4", ContextWindow: 200000, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "claude-haiku-4-5-20251001", Name: "Claude Haiku 3.5", ContextWindow: 200000, Capabilities: []string{"chat", "vision", "tools"}},
		},
	},
	{
		ID:             "google",
		Name:           "Google Gemini",
		IconEmoji:      "💎",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://generativelanguage.googleapis.com/v1beta",
		AuthLabel:      "API Key",
		Adapter:        "google",
		DocsURL:        "https://ai.google.dev/docs",
		Models: []ModelDef{
			{ID: "gemini-2.0-flash", Name: "Gemini 2.0 Flash", ContextWindow: 1048576, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "gemini-2.0-pro", Name: "Gemini 2.0 Pro", ContextWindow: 1048576, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "gemini-1.5-pro", Name: "Gemini 1.5 Pro", ContextWindow: 2097152, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "text-embedding-004", Name: "Text Embedding 004", ContextWindow: 2048, Capabilities: []string{"embed"}},
		},
	},
	{
		ID:             "xai",
		Name:           "xAI / Grok",
		IconEmoji:      "🚀",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://api.x.ai/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.x.ai",
		Models: []ModelDef{
			{ID: "grok-2", Name: "Grok 2", ContextWindow: 131072, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "grok-2-mini", Name: "Grok 2 Mini", ContextWindow: 131072, Capabilities: []string{"chat", "tools"}},
		},
	},
	{
		ID:             "mistral",
		Name:           "Mistral",
		IconEmoji:      "🌬️",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://api.mistral.ai/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.mistral.ai",
		Models: []ModelDef{
			{ID: "mistral-large-latest", Name: "Mistral Large", ContextWindow: 128000, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "mistral-small-latest", Name: "Mistral Small", ContextWindow: 128000, Capabilities: []string{"chat", "tools"}},
			{ID: "codestral-latest", Name: "Codestral", ContextWindow: 32000, Capabilities: []string{"chat", "tools"}},
			{ID: "mistral-embed", Name: "Mistral Embed", ContextWindow: 8192, Capabilities: []string{"embed"}},
		},
	},
	{
		ID:             "cohere",
		Name:           "Cohere",
		IconEmoji:      "🧬",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://api.cohere.com/v2",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.cohere.com",
		Models: []ModelDef{
			{ID: "command-r-plus", Name: "Command R+", ContextWindow: 128000, Capabilities: []string{"chat", "tools"}},
			{ID: "command-r", Name: "Command R", ContextWindow: 128000, Capabilities: []string{"chat", "tools"}},
			{ID: "embed-english-v3.0", Name: "Embed English v3.0", ContextWindow: 512, Capabilities: []string{"embed"}},
		},
	},
	{
		ID:             "deepseek",
		Name:           "DeepSeek",
		IconEmoji:      "🔍",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://api.deepseek.com/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://platform.deepseek.com/docs",
		Models: []ModelDef{
			{ID: "deepseek-chat", Name: "DeepSeek Chat", ContextWindow: 128000, Capabilities: []string{"chat", "tools"}},
			{ID: "deepseek-reasoner", Name: "DeepSeek Reasoner", ContextWindow: 128000, Capabilities: []string{"chat"}},
		},
	},
	{
		ID:             "ai21",
		Name:           "AI21",
		IconEmoji:      "🧪",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://api.ai21.com/studio/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.ai21.com",
		Models: []ModelDef{
			{ID: "jamba-1.5-large", Name: "Jamba 1.5 Large", ContextWindow: 256000, Capabilities: []string{"chat", "tools"}},
			{ID: "jamba-1.5-mini", Name: "Jamba 1.5 Mini", ContextWindow: 256000, Capabilities: []string{"chat", "tools"}},
		},
	},
	{
		ID:             "qwen",
		Name:           "Alibaba / Qwen",
		IconEmoji:      "☁️",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://help.aliyun.com/zh/model-studio/developer-reference/",
		Models: []ModelDef{
			{ID: "qwen-max", Name: "Qwen Max", ContextWindow: 32000, Capabilities: []string{"chat", "tools"}},
			{ID: "qwen-plus", Name: "Qwen Plus", ContextWindow: 131072, Capabilities: []string{"chat", "tools"}},
			{ID: "qwen-turbo", Name: "Qwen Turbo", ContextWindow: 131072, Capabilities: []string{"chat", "tools"}},
		},
	},
	{
		ID:             "zhipu",
		Name:           "Zhipu / GLM",
		IconEmoji:      "🧠",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://open.bigmodel.cn/api/paas/v4",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://open.bigmodel.cn/dev/howuse/introduction",
		Models: []ModelDef{
			{ID: "glm-4-plus", Name: "GLM-4 Plus", ContextWindow: 128000, Capabilities: []string{"chat", "tools"}},
		},
	},
	{
		ID:             "moonshot",
		Name:           "Moonshot / Kimi",
		IconEmoji:      "🌙",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://api.moonshot.cn/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://platform.moonshot.cn/docs",
		Models: []ModelDef{
			{ID: "moonshot-v1-128k", Name: "Moonshot v1 128K", ContextWindow: 128000, Capabilities: []string{"chat"}},
		},
	},
	{
		ID:             "minimax",
		Name:           "MiniMax",
		IconEmoji:      "⚡",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://api.minimax.chat/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://platform.minimaxi.com/document/introduction",
		Models: []ModelDef{
			{ID: "abab6.5s-chat", Name: "ABAB 6.5s Chat", ContextWindow: 245760, Capabilities: []string{"chat"}},
		},
	},
	{
		ID:             "writer",
		Name:           "Writer",
		IconEmoji:      "✍️",
		Category:       "frontier",
		Tier:           "known",
		DefaultBaseURL: "https://api.writer.com/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://dev.writer.com/docs",
		Models: []ModelDef{
			{ID: "palmyra-x-004", Name: "Palmyra X 004", ContextWindow: 128000, Capabilities: []string{"chat", "tools"}},
		},
	},

	// ─── Cloud ────────────────────────────────────────────────────────────────

	{
		ID:             "aws_bedrock",
		Name:           "AWS Bedrock",
		IconEmoji:      "🪨",
		Category:       "cloud",
		Tier:           "known",
		DefaultBaseURL: "https://bedrock-runtime.us-east-1.amazonaws.com",
		AuthLabel:      "AWS Credentials",
		Adapter:        "bedrock",
		DocsURL:        "https://docs.aws.amazon.com/bedrock/",
		Models: []ModelDef{
			{ID: "anthropic.claude-3-5-sonnet-20241022-v2:0", Name: "Claude Sonnet 3.5 (Bedrock)", ContextWindow: 200000, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "amazon.nova-pro-v1:0", Name: "Amazon Nova Pro", ContextWindow: 300000, Capabilities: []string{"chat", "vision", "tools"}},
		},
	},
	{
		ID:             "azure",
		Name:           "Azure AI Foundry",
		IconEmoji:      "🔷",
		Category:       "cloud",
		Tier:           "known",
		DefaultBaseURL: "https://{resource}.openai.azure.com/openai/deployments/{deployment}",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://learn.microsoft.com/en-us/azure/ai-services/openai/",
		Models:         []ModelDef{},
	},
	{
		ID:             "vertex",
		Name:           "Google Vertex AI",
		IconEmoji:      "📐",
		Category:       "cloud",
		Tier:           "known",
		DefaultBaseURL: "https://{region}-aiplatform.googleapis.com/v1/projects/{project}/locations/{region}/publishers/google/models",
		AuthLabel:      "Service Account JSON",
		Adapter:        "google",
		DocsURL:        "https://cloud.google.com/vertex-ai/docs",
		Models:         []ModelDef{},
	},
	{
		ID:             "ibm_watsonx",
		Name:           "IBM watsonx",
		IconEmoji:      "🏢",
		Category:       "cloud",
		Tier:           "known",
		DefaultBaseURL: "https://us-south.ml.cloud.ibm.com/ml/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/fm-api.html",
		Models:         []ModelDef{},
	},
	{
		ID:             "databricks",
		Name:           "Databricks",
		IconEmoji:      "🧱",
		Category:       "cloud",
		Tier:           "known",
		DefaultBaseURL: "https://{workspace}.cloud.databricks.com/serving-endpoints",
		AuthLabel:      "Access Token",
		Adapter:        "openai",
		DocsURL:        "https://docs.databricks.com/en/machine-learning/model-serving/",
		Models:         []ModelDef{},
	},
	{
		ID:             "snowflake_cortex",
		Name:           "Snowflake Cortex",
		IconEmoji:      "❄️",
		Category:       "cloud",
		Tier:           "known",
		DefaultBaseURL: "https://{account}.snowflakecomputing.com/api/v2/cortex",
		AuthLabel:      "Bearer Token",
		Adapter:        "openai",
		DocsURL:        "https://docs.snowflake.com/en/user-guide/snowflake-cortex/llm-functions",
		Models:         []ModelDef{},
	},
	{
		ID:             "cloudflare_ai",
		Name:           "Cloudflare Workers AI",
		IconEmoji:      "🌐",
		Category:       "cloud",
		Tier:           "known",
		DefaultBaseURL: "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai",
		AuthLabel:      "API Token",
		Adapter:        "openai",
		DocsURL:        "https://developers.cloudflare.com/workers-ai/",
		Models:         []ModelDef{},
	},

	// ─── Inference ────────────────────────────────────────────────────────────

	{
		ID:             "groq",
		Name:           "Groq",
		IconEmoji:      "⚡",
		Category:       "inference",
		Tier:           "known",
		DefaultBaseURL: "https://api.groq.com/openai/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://console.groq.com/docs",
		Models: []ModelDef{
			{ID: "llama-3.3-70b-versatile", Name: "Llama 3.3 70B Versatile", ContextWindow: 128000, Capabilities: []string{"chat", "tools"}},
			{ID: "llama-3.1-8b-instant", Name: "Llama 3.1 8B Instant", ContextWindow: 128000, Capabilities: []string{"chat", "tools"}},
			{ID: "mixtral-8x7b-32768", Name: "Mixtral 8x7B", ContextWindow: 32768, Capabilities: []string{"chat"}},
			{ID: "gemma2-9b-it", Name: "Gemma 2 9B IT", ContextWindow: 8192, Capabilities: []string{"chat"}},
		},
	},
	{
		ID:             "cerebras",
		Name:           "Cerebras",
		IconEmoji:      "🧠",
		Category:       "inference",
		Tier:           "known",
		DefaultBaseURL: "https://api.cerebras.ai/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.cerebras.ai",
		Models:         []ModelDef{},
	},
	{
		ID:             "together",
		Name:           "Together AI",
		IconEmoji:      "🤝",
		Category:       "inference",
		Tier:           "known",
		DefaultBaseURL: "https://api.together.xyz/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.together.ai",
		Models:         []ModelDef{},
	},
	{
		ID:             "fireworks",
		Name:           "Fireworks AI",
		IconEmoji:      "🎆",
		Category:       "inference",
		Tier:           "known",
		DefaultBaseURL: "https://api.fireworks.ai/inference/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.fireworks.ai",
		Models:         []ModelDef{},
	},
	{
		ID:             "deepinfra",
		Name:           "DeepInfra",
		IconEmoji:      "🏗️",
		Category:       "inference",
		Tier:           "known",
		DefaultBaseURL: "https://api.deepinfra.com/v1/openai",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://deepinfra.com/docs",
		Models:         []ModelDef{},
	},
	{
		ID:             "sambanova",
		Name:           "SambaNova",
		IconEmoji:      "💨",
		Category:       "inference",
		Tier:           "known",
		DefaultBaseURL: "https://api.sambanova.ai/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.sambanova.ai",
		Models:         []ModelDef{},
	},
	{
		ID:             "replicate",
		Name:           "Replicate",
		IconEmoji:      "🔄",
		Category:       "inference",
		Tier:           "known",
		DefaultBaseURL: "https://api.replicate.com/v1",
		AuthLabel:      "API Token",
		Adapter:        "openai",
		DocsURL:        "https://replicate.com/docs",
		Models:         []ModelDef{},
	},
	{
		ID:             "perplexity",
		Name:           "Perplexity AI",
		IconEmoji:      "🔎",
		Category:       "inference",
		Tier:           "known",
		DefaultBaseURL: "https://api.perplexity.ai",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.perplexity.ai",
		Models: []ModelDef{
			{ID: "sonar-pro", Name: "Sonar Pro", ContextWindow: 200000, Capabilities: []string{"chat"}},
			{ID: "sonar", Name: "Sonar", ContextWindow: 128000, Capabilities: []string{"chat"}},
		},
	},
	{
		ID:             "runpod",
		Name:           "RunPod",
		IconEmoji:      "🏃",
		Category:       "inference",
		Tier:           "known",
		DefaultBaseURL: "https://api.runpod.ai/v2",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.runpod.io",
		Models:         []ModelDef{},
	},
	{
		ID:             "lambda",
		Name:           "Lambda Labs",
		IconEmoji:      "🐑",
		Category:       "inference",
		Tier:           "known",
		DefaultBaseURL: "https://api.lambdalabs.com/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.lambdalabs.com",
		Models:         []ModelDef{},
	},
	{
		ID:             "novita",
		Name:           "Novita AI",
		IconEmoji:      "✨",
		Category:       "inference",
		Tier:           "known",
		DefaultBaseURL: "https://api.novita.ai/v3/openai",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://novita.ai/docs",
		Models:         []ModelDef{},
	},
	{
		ID:             "hyperbolic",
		Name:           "Hyperbolic",
		IconEmoji:      "📈",
		Category:       "inference",
		Tier:           "known",
		DefaultBaseURL: "https://api.hyperbolic.xyz/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.hyperbolic.xyz",
		Models:         []ModelDef{},
	},

	// ─── Gateways ─────────────────────────────────────────────────────────────

	{
		ID:             "openrouter",
		Name:           "OpenRouter",
		IconEmoji:      "🔀",
		Category:       "gateway",
		Tier:           "gateway",
		DefaultBaseURL: "https://openrouter.ai/api/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://openrouter.ai/docs",
		Models: []ModelDef{
			{ID: "openai/gpt-4o", Name: "GPT-4o (via OpenRouter)", ContextWindow: 128000, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "anthropic/claude-sonnet-4-6", Name: "Claude Sonnet 4 (via OpenRouter)", ContextWindow: 200000, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "google/gemini-2.0-flash-001", Name: "Gemini 2.0 Flash (via OpenRouter)", ContextWindow: 1048576, Capabilities: []string{"chat", "vision", "tools"}},
			{ID: "meta-llama/llama-3.1-405b-instruct", Name: "Llama 3.1 405B (via OpenRouter)", ContextWindow: 131072, Capabilities: []string{"chat", "tools"}},
		},
	},
	{
		ID:             "litellm",
		Name:           "LiteLLM",
		IconEmoji:      "🪶",
		Category:       "gateway",
		Tier:           "gateway",
		DefaultBaseURL: "http://localhost:4000/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.litellm.ai",
		Models:         []ModelDef{},
	},
	{
		ID:             "portkey",
		Name:           "Portkey",
		IconEmoji:      "🔑",
		Category:       "gateway",
		Tier:           "gateway",
		DefaultBaseURL: "https://api.portkey.ai/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://portkey.ai/docs",
		Models:         []ModelDef{},
	},
	{
		ID:             "helicone",
		Name:           "Helicone",
		IconEmoji:      "☀️",
		Category:       "gateway",
		Tier:           "gateway",
		DefaultBaseURL: "https://oai.helicone.ai/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.helicone.ai",
		Models:         []ModelDef{},
	},
	{
		ID:             "bifrost",
		Name:           "Bifrost",
		IconEmoji:      "🌈",
		Category:       "gateway",
		Tier:           "gateway",
		DefaultBaseURL: "https://api.bifrost.ai/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.bifrost.ai",
		Models:         []ModelDef{},
	},
	{
		ID:             "kong_ai",
		Name:           "Kong AI Gateway",
		IconEmoji:      "🦍",
		Category:       "gateway",
		Tier:           "gateway",
		DefaultBaseURL: "http://localhost:8000",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.konghq.com/gateway/latest/ai-gateway/",
		Models:         []ModelDef{},
	},
	{
		ID:             "martian",
		Name:           "Martian",
		IconEmoji:      "👽",
		Category:       "gateway",
		Tier:           "gateway",
		DefaultBaseURL: "https://api.withmartian.com/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.withmartian.com",
		Models:         []ModelDef{},
	},
	{
		ID:             "unify",
		Name:           "Unify AI",
		IconEmoji:      "🔗",
		Category:       "gateway",
		Tier:           "gateway",
		DefaultBaseURL: "https://api.unify.ai/v0",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.unify.ai",
		Models:         []ModelDef{},
	},
	{
		ID:             "neutrino",
		Name:           "Neutrino",
		IconEmoji:      "⚛️",
		Category:       "gateway",
		Tier:           "gateway",
		DefaultBaseURL: "https://router.neutrinoapp.com/v1",
		AuthLabel:      "API Key",
		Adapter:        "openai",
		DocsURL:        "https://docs.neutrinoapp.com",
		Models:         []ModelDef{},
	},
}

// GetProviderDef looks up a provider by ID.
func GetProviderDef(id string) (ProviderDef, bool) {
	for _, p := range ProviderRegistry {
		if p.ID == id {
			return p, true
		}
	}
	return ProviderDef{}, false
}

// ProvidersByCategory returns all providers matching the given category.
func ProvidersByCategory(category string) []ProviderDef {
	var out []ProviderDef
	for _, p := range ProviderRegistry {
		if p.Category == category {
			out = append(out, p)
		}
	}
	return out
}
